version: '3'
services:
    web:
        build:
            context: .
            dockerfile: .docker/web.docker
        volumes:
            - .:/var/www
        ports:
            - '4443:443'
        links:
            - app
    app:
        build:
            context: .
            dockerfile: .docker/app.docker
        volumes:
            - .:/var/www
        links:
            - db
        environment:
            - 'DB_PORT=3306'
            - 'DB_HOST=db'
    db:
        build:
            context: .
            dockerfile: .docker/db.docker
        volumes:
            - ./assets/db:/var/lib/mysql
        ports:
            - '6306:3306'
        environment:
            - 'MYSQL_ROOT_PASSWORD=root'
